M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu22.04.1} date 2025-06-23T11:59:28+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-23T11:59:28+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X110.6Y-37.61
X110.6Y-43.39
M30
